@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Creating initial commit...
git commit -m "Initial commit"
echo Setting up remote repository...
git remote add origin https://github.com/highlander-10/tastetest.git
echo Pushing to GitHub...
git push -u origin main
